version: '3.8'
services:
  ai_app:
    build: .
    container_name: Qwen-Image-Edit-Angles
    ports:
      - "7860:7860"
    volumes:
      - /workspace/hf_cache:/workspace/hf_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - PYTHONUNBUFFERED=1